import os
import cv2
import numpy as np
import sqlite3
import ezdxf
import matplotlib.pyplot as plt
from shapely.geometry import Polygon, MultiPolygon, MultiPoint
from shapely.ops import unary_union
from shapely.affinity import rotate
from rectpack import newPacker
from request.mapped_DXF import embed_request_to_rec,embed_nesting_to_rec
from request.request_rec import request_rec_output, request_rec_output_nesting
from request.request_nest import nest
from request.config import MASK_SCALE,STEP_SIZE_MM,ROTATION_ANGLES,VERBOSE
import os 

# 设置输入输出路径
request_path = "requestTest/rTest8.dxf"  #the requested dxf 
nest_request_path = "requestTest/nestrTest8.dxf"  # nested file(generated by program)
dxf_output_path = "requestTest/out8.dxf" # the output dxf of board with request on it 
rec = (15.566816620773984, -23.750606449707448, 61.0, 32.0) # the returned (x,y,w,h) from database, it is define here since I have no access to database
nest(request_path,7,nest_request_path) # give the nested of 7 requested shape.
request_rec_output(nest_request_path) # take that nested and find their min out rec--return width, height
##here you use width, height to request a fittest rec and it's board in database.
rec = (15.566816620773984, -23.750606449707448, 61.0, 32.0) # the returned (x,y,w,h) from database, it is define here since I have no access to database
board_path = "out/test5.dxf" # board in database

embed_nesting_to_rec(nest_request_path,board_path,rec,dxf_output_path) #give the output dxf of board with request on it 
